build: false
environment:
  matrix:
    - TOXENV: check
    - TOXENV: "2.7-1.3"
    - TOXENV: "2.7-1.4"
    - TOXENV: "3.4-1.3"
    - TOXENV: "3.4-1.4"
init:
  - "ECHO %TOXENV%"
  - ps: "ls C:\\Python*"
install:
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/ez_setup.py" -OutFile "c:\\ez_setup.py"
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/get-pip.py" -OutFile "c:\\get-pip.py"
  - "c:\\python27\\python c:\\ez_setup.py"
  - "c:\\python27\\python c:\\get-pip.py"
  - "c:\\python27\\Scripts\\pip install tox virtualenv"
test_script:
  - "c:\\python27\\Scripts\\tox --version"
  - "c:\\python27\\Scripts\\virtualenv --version"
  - "c:\\python27\\Scripts\\pip --version"
  - "c:\\python27\\Scripts\\tox"
